### ISSUE TITLE
PHP Fatal error OpenPgpWebclient Module.php

### ISSUE THREAD

**Issue by EHCanadian** [afterlogic/webmail-pro-8#14]
`
[10-Jan-2024 01:18:26 America/Toronto] PHP Fatal error:  Uncaught Error: Call to a member function GetContactsInfo() on false in \webmail\public_html\modules\OpenPgpWebclient\Module.php:396
Stack trace:
#0 [internal function]: Aurora\Modules\OpenPgpWebclient\Module->GetPublicKeysFromContacts(7)
#1 \public_html\system\Module\AbstractModule.php(811): call_user_func_array(Array, Array)
#2 \webmail\public_html\modules\Core\Module.php(665): Aurora\System\Module\AbstractModule->CallMethod('GetPublicKeysFr...', Array, true)
#3 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#4 \webmail\public_html\system\Router.php(103): call_user_func_array(Array, Array)
#5 \webmail\public_html\system\Module\Manager.php(607): Aurora\System\Router->route('api')
#6 \webmail\public_html\system\Application.php(132): Aurora\System\Module\Manager->RunEntry('api')
#7 \webmail\public_html\system\Application.php(100): Aurora\System\Application->Route('api')
#8 \webmail\public_html\index.php(21): Aurora\System\Application::Start()
#9 {main}
  thrown in \webmail\public_html\modules\OpenPgpWebclient\Module.php on line 396
`

Not sure if this is due to a module (*.json) that been set to disable but has a dependency?

9.7.5.build12-build-o3
PHP 8.3.1 (cli) (built: Dec 20 2023 14:06:10)

**Comment by afterlogic-support** [comment]
We've deployed a test instance of Ubuntu server with Apache and PHP 8.3.1 running there, and weren't able to reproduce the issue. Does this occur on a blank installation, or only after you reconfigure some of the modules? If that's the latter, can you narrow it down to specific module(s)?

Also, can you switch to a different PHP version - say, 8.1 or even 7.4 - and see if the issue is caused by PHP version used at all?

**Comment by EHCanadian** [comment]
Looks like its present as well with a fresh install.

This shows up as well on the web interface.

`Data transfer has failed, probably due to server error. Please contact system administrator.`

Fallowed by a php error log entry. `PHP Fatal error:  Uncaught Error: Call to a member function GetContactsInfo() ....`

A email count exist on the inbox folder, Nothing data/row wise for that email folder populates. (inbox)
You can navigate to the other folders and if email exist, It does populate.

I can purge the inbox from the server side, The error goes away.

Update: 01-14-2024

\vendor\afterlogic\mailso\lib\MailSo\Base\Utils.php

From Line: 387 \function_exists('utf8_encode')):
To   Line: 387 \function_exists('mb_convert_encoding')):

From Line: 398 $sResult = \utf8_encode($sResult);
To   Line: 398 $sResult = \mb_convert_encoding($sResult,'UTF-8', mb_list_encodings());

From Line: 394 \function_exists('utf8_decode')):
To   Line: 394 \function_exists('mb_convert_encoding')):

From Line: 396 $sResult = \utf8_decode($sResult);
To   Line: 396 \mb_convert_encoding($sResult, 'ISO-8859-1', 'UTF-8');

Data rows populates. No php error log entry now.

**Comment by afterlogic-support** [comment]
OK thank you for the update. I have notified the developers on this, will make sure they take a closer look at the issue.

**Comment by afterlogic-support** [comment]
I have just spoken to the developers on this. They do understand the nature of the fix you've suggested, however there's a slight confusion regarding this part here:

```php
$sResult = \mb_convert_encoding($sResult,'UTF-8', mb_list_encodings());
```

Is there a reason why the encoding isn't specified explicitly? Does it work for you if you put the code as follows:

```php
$sResult = \mb_convert_encoding($sResult,'UTF-8', 'ISO-8859-1');
```

With regard to fatal error you've encountered, the developers are led to believe that the error in question isn't related to the actual issue with accessing emails and folders. The method used there is typically invoked when you view public keys from the Personal address book, in OpenPGP tab of account settings. 

So we're wondering, if you temporarily rollback the fix, are you still getting fatal error in OpenPgpWebclient module even if you only access the mails and not contacts or settings? Our guess is, a different error should be there in the logs in such a case - deprecation-related warning, for example.

Thank you.

**Comment by EHCanadian** [comment]
https://www.php.net/manual/en/function.mb-list-encodings.php

I only speak US English, So I don't have to worry about displaying any other supported language on my use.

But yes, replacing mb_list_encodings() with ISO-8859-1 does work :)

**Comment by afterlogic-support** [comment]
Thank you for the response. Our developers have another question: you've mentioned disabling some modules, could you let us know which of the modules you've disabled - out of those initially enabled, that is? 

We're particularly wondering about Contacts module, did you have it disabled? Because frankly speaking, such a scenario was never tested; if you require contacts functionality to be hidden from web interface, we recommend disabling ContactsWebclient module instead. 

Thanks.

**Comment by EHCanadian** [comment]
Everything was disabled. I had tried enabling and disabling,
even browser cache clearing for that webmail domain after enabling and disabling the modules.

Thou it made no difference, even with a fresh install. 

Even with Contacts and OpenPgp toggled states of enabled or disabled, `PHP Fatal error:  Uncaught Error: Call to a member function GetContactsInfo() ....` would fire.

Initially all modules enabled or disabled didn't matter after setting up a temp fresh install.

Things functioned but once a certain type of email (wasn't able to track down exactly what one it was) was in the users inbox and webmail tried to utf8_encode it. That was the end of it. `Data transfer has failed ...`

Took a bit to track down the issue code side, as I wasn't understanding why OpenPgp was even being used when set to true to disable in the .json @ data/settings/modules

Only other thing I can help you out with was the smtp system was using hmailserver with imap.

**Comment by afterlogic-support** [comment]
We're now working on releasing version 9.7.6, could you please try [the release candidate build](https://afterlogic.com/download/webmail-pro-php-976-rc.zip) and confirm that the error is indeed corrected there? Thank you!

**Comment by EHCanadian** [comment]
So far with nothing enabled or disabled via .json module with a fresh install.

`[03-Feb-2024 07:14:53 America/Toronto] PHP Warning:  Trying to access array offset on false in \webmail\public_html\modules\OpenPgpWebclient\Module.php on line 444

[03-Feb-2024 07:14:54 America/Toronto] PHP Deprecated:  Function utf8_encode() is deprecated in \webmail\public_html\vendor\afterlogic\mailso\lib\MailSo\Base\Utils.php on line 389`

After going though a few pages in a inbox with some emails...

Data transfer has failed, probably due to server error. Please contact system administrator.

`[03-Feb-2024 07:37:39 America/Toronto] PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in \webmail\public_html\vendor\afterlogic\mailso\lib\MailSo\Base\Utils.php on line 174`

Fixed the strtolower by adding the below above $sEncoding = \strtolower($sEncoding);

`if(is_null($sEncoding)){$sEncoding = 'utf8';};`

**Comment by EHCanadian** [comment]
[13:15:58.08][c2f11de8] IMAP[DATA]: < TAG6 OK UID completed\r\n
[13:15:58.08][c2f11de8] IMAP[DATA]: > TAG7 UID FETCH 87716,87715,87714,87713,87712,87711,87710,87709,87708,87707 (UID RFC822.SIZE INTERNALDATE FLAGS BODYSTRUCTURE BODY.PEEK[HEADER])\r\n

[13:15:58.08][c2f11de8] IMAP[DATA]: < * 676 FETCH (UID 87712 RFC822.SIZE 1991 FLAGS () INTERNALDATE " 2-Feb-2024 20:14:12 -0500" BODYSTRUCTURE ("APPLICATION" "GZIP" ("NAME" "mimecast.org!domain.com!1706745600!1706831999!513fd8f805d80bd7f20326982a1d4b4f129bc600d35e719f6a916e90acf8c176.xml.gz.txt") NIL "Report domain: domain.com Submitter: mimecast.org Report-ID: 513fd8f805d80bd7f20326982a1d4b4f129bc600d35e719f6a916e90acf8c176" "quoted-printable" 262 NIL ("attachment" ("FILENAME" "mimecast.org!domain.com!1706745600!1706831999!513fd8f805d80bd7f20326982a1d4b4f129bc600d35e719f6a916e90acf8c176.xml.gz.txt"))) BODY[HEADER] {1709}\r\n

[13:15:58.09][c2f11de8] IMAP[DATA]: < )\r\n
[13:15:58.09][c2f11de8] IMAP[DATA]: < TAG7 OK UID completed\r\n
[13:15:58.10][c2f11de8] PHP[NOTICE]: C:\SrvData\Domains\webmail\public_html\vendor\afterlogic\mailso\lib\MailSo\Base\Utils.php [line:174, code:8192]
[13:15:58.10][c2f11de8] PHP[NOTICE]: Error: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

if I delete the email from mimecast.org via office 365 outlook, refresh the webpage, The paged data displays. GZIP email attachments are disabled extensions on the smtp.

**Comment by afterlogic-support** [comment]
Thank you. It appears the main error in question is gone so this can be closed. Though I can see a few warnings in the output, none of those look critical, they can be suppressed by adjusting error_reporting / display_errors PHP configuration settings, on production systems those warnings typically are written to the logs but are not actually displayed.

Thanks again!
