### ISSUE TITLE
After successful login page

### ISSUE THREAD

**Issue by EHCanadian** [afterlogic/webmail-pro-8#15]
I do not see a settings that allows one to configure what "tab" a successful login directs to.

After enabling a few plugins such a files, calendar, The /#mail is no longer the default page. Calendar is now the default.

Edit: MailLoginFormWebclient

**Comment by afterlogic-support** [comment]
Please check `data/settings/modules/CoreWebclient.config.json` configuration file - in this file, "HeaderModulesOrder" shows the list of screens and the order they're listed in, while "DefaultUserScreenHash" points to a default screen.

I hope this helps.

**Comment by EHCanadian** [comment]
Worked when "mail" was inserted.
