### ISSUE TITLE
Web API Error - Mail/GetMessage

### ISSUE THREAD

**Issue by lankahost-dev** [afterlogic/webmail-pro-8#16]
I am trying to fetch a content of email using the API. But it end up with  "ErrorCode": 108. Can you please advise ?

Module : https://afterlogic.com/webmail-pro-8-webapi/#api-Mail-GetMessage

![image](https://github.com/afterlogic/webmail-pro-8/assets/18673508/68e31449-582c-4a2a-8141-6347b8d48b67)

The response I am getting is below

![image](https://github.com/afterlogic/webmail-pro-8/assets/18673508/57bfa1e5-5c8d-48b9-969e-ed8010bbd860)

I was able to use other API methods without any issue. Also enabled the debug and here is what it logged 

```
[02:57:41.97][62712c91]  ===== ENTRY: Core::api
[02:57:41.97][62712c91]  URL: /afterlogic/?/Api/
[02:57:41.97][62712c91]  
[02:57:41.97][62712c91]  ===== API: Mail::GetMessage
[02:57:41.97][62712c91] Exception[1105]: 
~ /modules/mail/managers/accounts/manager.php (43)

----------------------------------------------------------------------
#0 /var/www/html/afterlogic/modules/Mail/Module.php(3080): Aurora\Modules\Mail\Managers\Accounts\Manager->getAccountById()
#1 [internal function]: Aurora\Modules\Mail\Module->GetMessage()
#2 /var/www/html/afterlogic/system/Module/AbstractModule.php(833): call_user_func_array()
#3 /var/www/html/afterlogic/modules/Core/Module.php(668): Aurora\System\Module\AbstractModule->CallMethod()
#4 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#5 /var/www/html/afterlogic/system/Router.php(105): call_user_func_array()
#6 /var/www/html/afterlogic/system/Module/Manager.php(608): Aurora\System\Router->route()
#7 /var/www/html/afterlogic/system/Application.php(132): Aurora\System\Module\Manager->RunEntry()
#8 /var/www/html/afterlogic/system/Application.php(102): Aurora\System\Application->Route()
#9 /var/www/html/afterlogic/index.php(21): Aurora\System\Application::Start()
#10 {main}
```

**Comment by afterlogic-support** [comment]
The error means you're attempting to access account the authenticated user doesn't have access to. My guess is, you supply User's ID for the AccountID but that's not a correct way. You can get the AccountID with **GetAuthenticatedAccount** method of **Core** module (the method doesn't have any parameters) and then use the Id you obtain for dealing with an account.

On a sidenote, Uid in GetMessage should be string - though most likely, it would work either way.
