### ISSUE TITLE
Don't ship dev dependencies in ZIP file

### ISSUE THREAD

**Issue by bohwaz** [afterlogic/webmail-pro-8#17]
When downloading ZIP files of Webmail Pro 8 from Afterlogic website, you get dev dependencies, and also the "dev" directory.

These are not useful in production and could also lead to security issues.

Just removing the dev directory and phpstan, it is 63 MB!

**Comment by afterlogic-support** [comment]
The dev directory is shipped by-design, currently we're not aware of any security issues related to that.
