### ISSUE TITLE
Private files are exposed by the web server

### ISSUE THREAD

**Issue by bohwaz** [afterlogic/webmail-pro-8#18]
The .htaccess file should block access to private files:

* vendor directory
* system directory
* non-public files in modules directory
* composer files
* VERSION file

A solution would be something like this:

```
RedirectMatch 404 modules/(.*(?!\.(css|js|png|webp|jpg|vue)))$
RedirectMatch 404 vendor/.*$
RedirectMatch 404 system/.*$
RedirectMatch 404 composer\..*$
RedirectMatch 404 VERSION$
RedirectMatch 404 LICENSE$
RedirectMatch 404 config\.json.*$

```

**Comment by afterlogic-support** [comment]
We do not consider those files private. VERSION and LICENSE files are safe to be removed, and *config.json files are protected separately.
