### ISSUE TITLE
MySQL 5.5 required

### ISSUE THREAD

**Issue by darnux** [afterlogic/webmail-pro-8#2]
Some tables in 
`modules/Dav/Storages/Db/Sql/create.sql`
are created with Charset utf8mb4 which breaks compability with MySQL versions older than MySQL 5.5.

Possible workaround pre-install:

`sed -i 's/CHARSET=utf8mb4;/CHARSET=utf8;/g' modules/Dav/Storages/Db/Sql/create.sql`

**Comment by sash04ek** [comment]
We are using 3rdparty 'sabre/dav' library, it requires `utf8mb4` character set to work correctly.
Webmail Pro 8 requires MySQL 5.5 or higher.
