### ISSUE TITLE
Paranoid Encryption for the Notes section

### ISSUE THREAD

**Issue by digimon99** [afterlogic/webmail-pro-8#3]
Hi, 

Will be great if users are able to encrypt the notes with the Paranoid Encryption, ideally using the same key as the files encryption.

Is this even possible? Since the Notes is a imap folder at the backend.

Thanks,

**Comment by afterlogic-support** [comment]
Hi,

I believe OpenPGP (which is supported for email) would make more sense for Notes (and will be easier to adapt for Notes). Paranoid Encryption is intended for encrypting file content (OpenPGP is not good for that).
