### ISSUE TITLE
Not able to save settings in admin.

### ISSUE THREAD

**Issue by Mike-the-one** [afterlogic/webmail-pro-8#4]
Tried to install the zip from here: https://afterlogic.com/download/webmail-pro, javascript console (chrome) has error, and not able to save the setting in admin.  Can click the save button (it changes to saving.,..) but nothing happens, no network activity.

Then, tried the latest.zip from this repo, missing package.json thus npm install doesn't work.

Then, tried to run git clone this repo, per the instruction, no js error in chrome debug console, but 
still cannot save.  Same as before, can click save, but nothing happens.

**Comment by afterlogic-support** [comment]
Have just answered this at: https://s.afterlogic.com/forum/forum_posts.asp?TID=7705
Also, we're going to release an update later today, will look into the files missing. Thanks.
