### ISSUE TITLE
Session stays alive on server after "logout"

### ISSUE THREAD

**Issue by HenkPoley** [afterlogic/webmail-pro-8#5]
I got a user who mentions that they sometimes (probably) see the CoreWebClient ERROR_USER_DELETED string right after/during logout. Or at least that's the closest string to the possibly jumbled up message I got through 'the telephone game'.

So my first angle was that maybe the javascript keeps requesting Api updates _during_ logout, and then hits the Api while you are actually already logged out.

To test this I tried replaying one of the last XHR requests in Edge Chromium. Which _does not_ execute. I guess because a session cookie was supposed to be invalidated.

----

So I used the 'Export to cURL' option. Which leads me to the actual issue of this ticket.

If you run the cURL command, you still get proper responses from the Api. So even though the Api sends a cookie invalidation message, it still keeps the session cookie or Bearer token on the server alive, and everything else connected to the logged in user.

Pretty-printed example response after sending  "Module: Core, Method: Logout", notice `AuthenticatedUserId":4`, `"MessageCount":2` and `"FolderHash"` being populated.

```json
{
   "AuthenticatedUserId":4,
   "@Time":0.6703,
   "Module":"Mail",
   "Method":"GetMessages",
   "Result":{
      "@Object":"Collection\/MessageCollection",
      "@Count":0,
      "@Collection":[
         
      ],
      "Uids":[
         
      ],
      "UidNext":"206",
      "FolderHash":"593ced41306e980437d33da09880c917",
      "MessageCount":2,
      "MessageUnseenCount":0,
      "MessageResultCount":0,
      "FolderName":"INBOX",
      "Offset":0,
      "Limit":200,
      "Search":"",
      "Filters":"flagged",
      "New":[
         
      ]
   },
   "SubscriptionsResult":null,
   "@TimeApiInit":0.4405
}
```

So whatever happens, at least the session seems to get revived. Possibly the Bearer token is not invalidated. And in this request at least some data leaks.

I can also get 'GetQuota' data, so probably everything the user sees can be accessed.

Maybe related to: https://github.com/afterlogic/webmail-lite-8/issues/78

**Comment by afterlogic-support** [comment]
Deleting a cookie doesn't invalidate a token, auth tokens are permanent by their nature - i.e. issuing a token doesn't actually start a session as such. So if a request with token was sent through, it will be processed even if cookie was already deleted.

Currently, the only way to invalidate such a token is to configure WebMail Pro for storing auth tokens in the database, it's done by setting "StoreAuthTokenInDB" to **true** in `data/settings/config.json` file; note that setting such an option assumes you already have the database configured.
