### ISSUE TITLE
Can't login with account created via API 

### ISSUE THREAD

**Issue by IgorKhomenko** [afterlogic/webmail-pro-8#6]
HI everyone 

we use https://afterlogic.com/webmail-pro-8-webapi/#api-Mail-CreateAccount to create an account which works well 

But then we try to login using newly created account - either via api or web - getting an auth error 

```
 {
  AuthenticatedUserId: 0,
  '@Time': 0.0588,
  SubscriptionsResult: null,
  '@TimeApiInit': 0.03,
  '@LoggerGuid': 'd34991b8',
  ErrorCode: 102,
  Module: ''
}
```

could you please assist what can be wrong 

we use DoImapLoginOnAccountCreate=false config, 
otherwise, when use true, we can't create an account either - failed with `ErrorMessage: ‘TAG1 NO (AUTHENTICATIONFAILED) Authentication failed.’,`

**Comment by IgorKhomenko** [comment]
Mainly following this guide https://afterlogic.com/docs/webmail-pro-8/developers-guide/managing-mail-servers-and-user-accounts

**Comment by afterlogic-support** [comment]
You need to make sure the account in question actually exists on IMAP server. You can only log into WebMail using actual email account. And usually, creating an account isn't required - just ensure mail server parameters are specified correctly in admin panel.
