### ISSUE TITLE
Calendar module for mobile 

### ISSUE THREAD

**Issue by IgorKhomenko** [afterlogic/webmail-pro-8#7]
Hi everyone

We found that Calendar module is available only for Web app

<img width="315" alt="Screenshot 2021-07-12 at 17 21 22" src="https://user-images.githubusercontent.com/70977170/125304074-f352e500-e335-11eb-876b-87fdaa8c1897.png">

Is there a ready module for mobile ?

Thank you

**Comment by afterlogic-support** [comment]
There currently isn't one, mobile version only includes email and contacts sections.
