### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by Joshndroid** [afterlogic/webmail-pro-8#8]
I feel the themes are a little lacking...
Typically these days everything has a bit of a dark theme.

Please implement a minimalist dark mode theme

**Comment by afterlogic-support** [comment]
Hello,

I can confirm this is in the roadmap and we're going to implement it in the near future.

Please use the following resource for feature requests:
https://afterlogic.uservoice.com/forums/932335-webmail-pro

Thanks!
